version: '3.10'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile  
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://velho_oeste_user:vopassword@postgres:5432/velho_oeste_db
    volumes:
      - .:/app  
    container_name: velho-oeste

  postgres:
    image: postgres:latest
    container_name: velho-oeste-postgres
    environment:
      POSTGRES_USER: velho_oeste_user
      POSTGRES_PASSWORD: vopassword
      POSTGRES_DB: velho_oeste_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./velho-oeste/database/00_create_tables.sql:/docker-entrypoint-initdb.d/00_create_tables.sql

volumes:
  postgres_data:
