version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: oeste_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/create:/docker-entrypoint-initdb.d
      # - ./database/populating:/docker-entrypoint-initdb.d
      # - ./database/integrity_control:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
