version: '3.11'

services:
  db:
    image: postgres:latest
    container_name: oeste_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    volumes:
      pgdata:
